# Generated by Django 3.1.7 on 2021-10-23 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('classgroup', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=5)),
                ('card_id', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ewallet.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Payment', 'Payment'), ('Scan & Pay', 'Scan & Pay')], default='Payment', max_length=15)),
                ('description', models.CharField(choices=[('Canteen', 'Canteen'), ('Co-op', 'Co-op'), ('e-Store', 'e-Store'), ('School Fee', 'School Fee')], default='Canteen', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ewallet.parent')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.student')),
            ],
        ),
        migrations.CreateModel(
            name='ParentWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.parent')),
            ],
        ),
    ]
