# Generated by Django 3.2 on 2021-12-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.AddField(
            model_name='order',
            name='receive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Co-op', 'Co-op'), ('e-Store', 'e-Store'), ('School Fee', 'School Fee')], default='Online', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Payment', 'Payment')], default='Payment', max_length=15),
        ),
    ]
