# Generated by Django 3.2 on 2021-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0002_auto_20211224_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
