# Generated by Django 3.1.7 on 2021-11-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0004_auto_20211102_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='parent',
        ),
    ]
