# Generated by Django 3.2 on 2022-01-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, choices=[('Canteen', 'Canteen'), ('Co-op', 'Co-op'), ('e-Store', 'e-Store'), ('School Fee', 'School Fee')], default='-', max_length=15),
        ),
        migrations.CreateModel(
            name='Notifcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ewallet.parent')),
            ],
        ),
    ]
