# Generated by Django 3.1.7 on 2021-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0006_auto_20211103_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(choices=[('Online', 'Online'), ('Reload', 'Reload'), ('Canteen', 'Canteen'), ('Co-op', 'Co-op'), ('e-Store', 'e-Store'), ('School Fee', 'School Fee')], default='Online', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Payment', 'Payment'), ('Scan & Pay', 'Scan & Pay')], default='Payment', max_length=15),
        ),
    ]
