# Generated by Django 3.2 on 2022-01-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0007_auto_20220125_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, choices=[('Canteen', 'Canteen'), ('Co-op', 'Co-op'), ('e-Store', 'e-Store'), ('School Fee', 'School Fee')], max_length=15, null=True),
        ),
    ]
