# Generated by Django 3.1.7 on 2021-11-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0008_auto_20211105_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['name']},
        ),
    ]
