# Generated by Django 3.1.7 on 2021-11-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0009_auto_20211105_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='p_wallet',
        ),
    ]
