# Generated by Django 3.1.7 on 2021-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0012_order_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
