# Generated by Django 3.2 on 2021-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0014_auto_20211124_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card_id',
            field=models.CharField(max_length=10),
        ),
    ]
