# Generated by Django 3.2 on 2021-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0015_alter_student_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
