# Generated by Django 3.2 on 2021-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0016_alter_student_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentwallet',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentwallet',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classgroup',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='s_wallet',
        ),
        migrations.AddField(
            model_name='parent',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B')], default='1A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ParentWallet',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='StudentWallet',
        ),
    ]
