# Generated by Django 3.1.7 on 2021-11-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletAdmin', '0002_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
